"""License management endpoints"""
import logging
from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from typing import List
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from uuid import UUID

from app.core.database import get_session
from app.middleware.auth import get_current_user
from app.models.license_key import LicenseKey
from app.models.user import User

logger = logging.getLogger(__name__)
router = APIRouter()


class LicenseResponse(BaseModel):
    key: str
    createdAt: str
    revoked: bool


class GenerateLicenseResponse(BaseModel):
    key: str
    message: str


class ListLicensesResponse(BaseModel):
    licenses: List[LicenseResponse]


class RevokeLicenseResponse(BaseModel):
    message: str


@router.post("/generate", response_model=GenerateLicenseResponse)
async def generate_license(
    user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    """Generate a new license key for the current user"""
    try:
        # Create new license key (UUID is auto-generated by default)
        license_key = LicenseKey(userId=user.id)
        session.add(license_key)
        await session.flush()  # Flush to get the generated key
        
        logger.info(f"License key generated for user: {user.email}")
        
        return GenerateLicenseResponse(
            key=str(license_key.key),
            message="License key generated successfully"
        )
        
    except Exception as e:
        logger.error(f"Failed to generate license key: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to generate license key")


@router.get("/list", response_model=ListLicensesResponse)
async def list_licenses(
    user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    """List all license keys for the current user"""
    try:
        # Get all license keys for the user
        result = await session.execute(
            select(LicenseKey)
            .where(LicenseKey.userId == user.id)
            .order_by(LicenseKey.createdAt.desc())
        )
        licenses = result.scalars().all()
        
        return ListLicensesResponse(
            licenses=[
                LicenseResponse(
                    key=str(license.key),
                    createdAt=license.createdAt.isoformat(),
                    revoked=license.revoked
                )
                for license in licenses
            ]
        )
        
    except Exception as e:
        logger.error(f"Failed to list license keys: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to list license keys")


@router.delete("/{key}", response_model=RevokeLicenseResponse)
async def revoke_license(
    key: str,
    user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    """Revoke a license key"""
    try:
        # Convert key string to UUID
        try:
            key_uuid = UUID(key)
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid license key format")
        
        # Find the license key
        result = await session.execute(
            select(LicenseKey)
            .where(LicenseKey.key == key_uuid)
            .where(LicenseKey.userId == user.id)
        )
        license_key = result.scalar_one_or_none()
        
        if not license_key:
            raise HTTPException(status_code=404, detail="License key not found")
        
        if license_key.revoked:
            raise HTTPException(status_code=400, detail="License key already revoked")
        
        # Revoke the license key
        license_key.revoked = True
        await session.flush()
        
        logger.info(f"License key revoked: {key}")
        
        return RevokeLicenseResponse(message="License key revoked successfully")
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to revoke license key: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to revoke license key")
