services:
  - type: web
    name: ai-cleanup-ml
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HOST
        value: 0.0.0.0
      - key: LOG_LEVEL
        value: INFO
      - key: DEVICE
        value: cpu
      - key: TEXT_MODEL_NAME
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: IMAGE_MODEL_NAME
        value: openai/clip-vit-base-patch32
      - key: MODEL_CACHE_DIR
        value: /opt/render/project/src/models_cache
      - key: MAX_BATCH_SIZE
        value: 32
    healthCheckPath: /health
